#!/bin/sh

rm /etc/fstab.jail

rm /Library/MobileSubstrate/DynamicLibraries/!!!!_BreakThrough_8.dylib
rm /Library/MobileSubstrate/DynamicLibraries/!!!!_BreakThrough_8.plist
rm /Library/MobileSubstrate/DynamicLibraries/zzzz_BreakThrough_8.dylib
rm /Library/MobileSubstrate/DynamicLibraries/zzzz_BreakThrough_8.plist

declare -a cydia
cydia=($CYDIA)
if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}"
fi
