#!/bin/sh

mv /Library/MobileSubstrate/DynamicLibraries/!!!!_BreakThrough.dylib /Library/MobileSubstrate/DynamicLibraries/!!!!_BreakThrough_8.dylib
mv /Library/MobileSubstrate/DynamicLibraries/!!!!_BreakThrough.plist /Library/MobileSubstrate/DynamicLibraries/!!!!_BreakThrough_8.plist
mv /Library/MobileSubstrate/DynamicLibraries/zzzz_BreakThrough.dylib /Library/MobileSubstrate/DynamicLibraries/zzzz_BreakThrough_8.dylib
mv /Library/MobileSubstrate/DynamicLibraries/zzzz_BreakThrough.plist /Library/MobileSubstrate/DynamicLibraries/zzzz_BreakThrough_8.plist

declare -a cydia
cydia=($CYDIA)
if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}"
fi
